#!/bin/bash
echo "Please wait, installing..."
git clone -q https://github.com/RomanDesigner/script /home/$USER/bin/prepare/
cd /home/$USER/bin/prepare/ && chmod +x prepare
echo -ne "50%\r"
git clone https://github.com/RomanDesigner/script-patch /home/$USER/android/patches/
echo -ne "80%\r"
echo "Enter your password for making changes in .bashrc!"
echo ""
sudo echo "" >> ~/.bashrc
sudo echo "#ROM script on GitHub:" >> ~/.bashrc
sudo echo "export PATH=$PATH:/home/$USER/bin/prepare/" >> ~/.bashrc
echo -ne "100%, done. Enjoy prepare command!\r"
cd /home/$USER/bin/prepare/ && ./prepare

